import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import styles from '../styles/Home.module.css';

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>
        Create Next App
      </title>
      <meta content="Generated by create next app" name="description" />
      <link href="/favicon.ico" rel="icon" />
    </Head>

    <main className={styles.main}>
      <h1 className="title">
        Read
        {' '}
        <Link href="/posts/first-post">
          <a>
            this page!
          </a>
        </Link>
      </h1>
    </main>

  </div>
);

export default Home;
